example.staging:
  branch: master
  deploy_path: /srv/users/serverpilot/apps/staging-example
  stage: staging
  user: serverpilot

example.production:
  branch: master
  deploy_path: /srv/users/serverpilot/apps/example
  stage: production
  user: serverpilot
